### PR TITLE
Merge tnorbye/kdoc-formatter into ktfmt

### PR DESCRIPTION
**Pull request by nreid260**
I've confirmed that this fixes most (if not all) of our known issues with KDoc formatting.

Compared to https://github.com/facebook/ktfmt/pull/358 this version gets the KDoc tests running, and adds copyright headers.

@cgrushko @tnorbye

### CODE REVIEW

**Comment by davidtorosyan** [comment]
Thanks for the import @nreid260!

One question for you and @tnorbye, what's the algorithm for `optimal` reflow?

I ask because I lean towards just using greedy unless there's a good reason to use something more complicated - I'm worried about bikeshedding tweaks to the `optimal` algorithm over time.

**Comment by nreid260** [comment]
In testing, optimal seemed to equalize line lengths, which caused short words at line ends to be bumped to the next line. It looked ok/good, but as a user, I'd find it irritating that lines didn't fill.

**Comment by davidtorosyan** [comment]
Agreed. How about we turn off optimal for this integration, and have some follow-up work to remove the relevant code?

Alternatively we can promote it to a CLI option, but unless someone wants to argue for that I don't think it's worth it.

**Comment by nreid260** [comment]
I'm happy to continue using greedy until we have some motivation to change.

**Comment by tnorbye** [comment]
The idea behind optimal  instead of greedy is to avoid raggedness, which makes the text more pleasant looking -- see https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Minimum_raggedness .

The overall idea here is to make comments easier to read. I'm not particularly wedded to this; feel free to just go with greedy.

But I do want to make a strong case for the concept of having a maximum comment width *separate* from the line width. That one I really think kttfmt should adopt, even if it's different from the current defaults in ktfmt and java-formatter.

The idea here is that text is *not* like code. For code, you have a lot of nesting, so a long line width makes sense -- 100 characters, 140 characters. It allows deep nesting without the code looking awkward. But most code lines are not 140 characters wide; if they approach the 140 character column, they probably started deeply nested at column 100 with lots of whitespace on the left.

Comments however are not code; they are intended to be read. And very long lines are not readable. That's why books are in portrait orientation, not landscape, and why web sites typically use columns and responsive designs.

If I have a class comment in a file with max-line-width of 140, we should *NOT* flow the text to the full width at 140! Instead, we should have a separate comment width which limits the line widths to something more reasonable. I think a reasonable default is 72 characters.

This means that if you start a comment in code that is nested starting at column 110, then yes, the comment would wrap at column 140 just like the line width says. But if the comment starts further to the left, for example in column 20, then it would wrap at column 92 (20+72), such that each comment line is only 72 characters.

This is why kdocformatter has separate settings for max-line-width and max-comment-width. I really really hope you'll agree to use this setting for ktfmt.

**Comment by davidtorosyan** [comment]
Thanks for the explanation @tnorbye! I'll read about raggedness (from my testing so far I'm guessing we'll still go with greedy though) and I'll do some testing with the line length - I hadn't even thought of it.

**Comment by cgrushko** [comment]
@tnorbye, in the context of tracking upstream, how do you see kdocformatter going forward?
For example, if it continues existing as an independent library, we might want to make it easier to track it (e.g., keeping the original package name, placing in a subdir named after the version, etc.).

**Comment by cgrushko** [comment]
Re greedy vs optimal: I suggest we use whatever is similar to what we have now, and change to optimal in a subsequent PR.

Re comment width: interesting! I need to think about this :) I also think there's a difference between kdoc and inline comments, but I'd like some consistency. For now, again I suggest we stick to what looks similar to what we have now. (meaning, comment width == code width)

**Comment by davidtorosyan** [comment]
Going ahead with landing, here's the follow-ups:
1. We'll evaluate optimal vs greedy, and either (a) switch to optimal, (b) remove the optimal code.
2. I'll likely set `allowParamBrackets` to `false` for consistency
3. We'll expose `maxCommentWidth` as a parameter to the ktfmt CLI

@tnorbye / @nreid260 let us know if there's anything else we're missing. I'd like it if `ktfmt` can be used wherever `kdocformatter` was used before.

**Pull request closed without merging**
