### PR TITLE
Fix indentation of initializer-like expressions with leading comments

### PR DESCRIPTION
**Pull request by nreid260**

### CODE REVIEW

**Comment by nreid260** [comment]
https://github.com/facebook/ktfmt/issues/380

This one is chained off of https://github.com/facebook/ktfmt/pull/381

**Comment by cgrushko** [comment]
@nreid260  this needs rebasing because the PR underneath has landed

**Comment by nreid260** [comment]
Conflicts resolved.

**Comment by cgrushko** [comment]
This is great!! fixes a bunch of bad formatting internally. Thanks!!

**Pull request closed without merging**
