### PR TITLE
Support RangeUntil operator

### LINKED ISSUE #424: Kotlin rangeUntil ..< Syntax Throws Error
Using the abbreviated `rangeUntil` syntax `..<` throws an error during formatting

```kotlin
for (retries in 0 ..< MAX_RETRIES) {
  ...
}
```

```shell
Step 'ktfmt' found problem in 'src/test/kotlin/com/example/MyTest.kt':
112:29: error: Expecting an element
com.facebook.ktfmt.format.ParseError: 112:29: error: Expecting an element
        at com.facebook.ktfmt.format.Parser.throwParseError(Parser.kt:71)
        at com.facebook.ktfmt.format.Parser.parse(Parser.kt:65)
        at com.facebook.ktfmt.format.Formatter.sortedAndDistinctImports(Formatter.kt:143)
        at com.facebook.ktfmt.format.Formatter.format(Formatter.kt:90)
```

### PR DESCRIPTION
**Pull request by ArchdukeTim**
Fixes #424

### CODE REVIEW

**Comment by strulovich** [comment]
Hi @ArchdukeTim! thanks, this looks good to me to merge, but you will need to sign the CLA first.

**Comment by ArchdukeTim** [comment]
Signed. Need to wait for propagation

**Comment by austinarbor** [comment]
Any update on this?

**Comment by austinarbor-wk** [comment]
@strulovich @ArchdukeTim is there anything holding this back from getting merged in?

**Comment by austinarbor** [comment]
@strulovich @ArchdukeTim is there anything holding this back from getting merged in?

**Comment by hick209** [comment]
Sorry the delay @austinarbor. I'll pull your PR internally for review right away and will work with folks to get that merged in

**Pull request closed without merging**
