### PR TITLE
Upgrade IJ plugin to new IJP Gradle plugin 2.0

### PR DESCRIPTION
**Pull request by rock3r**
This is step 1/2 needed to be able to run the ktlint plugin on IJ 24.2, which was just released today to stable. The next step will be to actually fix the crash on 24.2 — another PR coming for that.

### CODE REVIEW

**Comment by hick209** [comment]
Thanks for the contributions here!
I see you also change the Java version to 17, is that a requirement? If so, you'd need to also update the GH workflow files accordingly
https://github.com/facebook/ktfmt/blob/main/.github/workflows/build_and_test.yml#L17
https://github.com/facebook/ktfmt/blob/main/.github/workflows/publish_artifacts_on_release.yaml#L29

**Comment by rock3r** [comment]
I have had a lot of pain trying to use an older JDK version than 17 with more recent tooling, so while not strictly mandatory, it's strongly advisable to. This still allows us to support 2 year old IJ versions.

I'll update the actions definition accordingly.

**Comment by rock3r** [comment]
All done, and rebased the other PRs on top

**Comment by hick209** [comment]
Looks like you still have errors in the build jobs

**Comment by rock3r** [comment]
@hick209 sorry! Difficult to test on a fork :)

**Comment by rock3r** [comment]
There was a failing test (not impacted by my changes), I fixed it...

**Review by hick209 — APPROVED** [review]

**Review by hick209 — APPROVED** [review]

**Comment by rock3r** [comment]
CI's green on my fork, hopefully we've gotten it to build again :)

**Comment by rock3r** [comment]
Yay!

**Comment by hick209** [comment]
Let's try to ship this! I just need approval from someone else from my team and we should be good to go.

**Comment by rock3r** [comment]
Aye. Hopefully y'all can cut a release soon. I built a zip with the version bumped to 1.2 for personal use in the meantime, so I can use ktfmt in IJ 24.2

**Comment by hick209** [comment]
Linter is failing for formatting, but I've fixed that internally already.
I'll try to merge this in and the other PRs today so we can cut a release yet this week 🚀

**Comment by rock3r** [comment]
Kind of odd the formatting is tripping up the linter, I ran spotlessApply...

**Comment by hick209** [comment]
That's on us, we haven't really setup spotless to format kotlin code. I'll try to fix that next

**Pull request closed without merging**
